[package]
name = "cqrs-todoql-psql"
version = "0.1.0"
authors = ["Marcus Griep <marcus@griep.us>"]
license = "Apache-2.0"
edition = "2018"
publish = false

[dependencies]
base64 = "0.10"
cqrs = { version = "0.3.1", path = "../cqrs" }
cqrs-postgres = { version = "0.3.3", path = "../cqrs-postgres" }
cqrs-todo-core = { version = "0.2.1", path = "../cqrs-todo-core" }
clap = "2.32"
chrono = "0.4"
env_logger = "0.6"
iron = "0.6"
juniper = "0.13"
juniper_codegen = "0.13"
juniper_iron = "0.5"
mount = "0.4"
num-traits = "0.2"
parking_lot = "0.9"
r2d2_postgres = "0.18.0"
r2d2 = "0.8"
serde = "1.0"
serde_json = "1.0"
hashids = { version = "1.0.0", git = "https://github.com/charsyam/hashids_rust.git" }
void = "1.0.2"